<a href="https://colab.research.google.com/github/dfirm/iads_day3/blob/main/Covid19_Twitter_SentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install Tweepy
!pip install tweepy

In [56]:
import re
import tweepy
from tweepy import OAuthHandler
consumer_api_key = ''
consumer_api_secret = '' 
access_token = ''
access_token_secret =''

In [57]:
authorizer = OAuthHandler(consumer_api_key, consumer_api_secret)
authorizer.set_access_token(access_token, access_token_secret)

In [58]:
api = tweepy.API(authorizer ,timeout=15)
all_tweets = []
search_query = 'COVID19'

for tweet_object in tweepy.Cursor(api.search,q=search_query+" -filter:retweets",lang='en',result_type='recent').items(200):
    all_tweets.append(tweet_object.text)
    print(tweet_object.text)

We can help beat #COVID19 together! Join me and take one minute a day to help fight the outbreak in our community.… https://t.co/qHWyGJNHqK
@Beatric84037839 @inthebubblepod @ASlavitt @pfizer @AlbertBourla But COVID19 is over with you/us. Therein lies the problem.
Fully vaccinated travellers from the #US and #EU countries will no longer need to undergo a 10-day compulsory… https://t.co/qf0Rdjo9IJ
Getting vaccinated is crucial to protecting everyone’s health. We’re proud of SCC's @AmCollSurgeons &amp; @aao_ophth fo… https://t.co/t9ej3hkvv6
For my mental health, I'm blocking everyone on my newsfeed that expresses ignorant-ass-commentary about SARS-COV-2… https://t.co/vxV7W72s6j
⚠️NYPOST: CDC warns #COVID19 may be a few mutations away from evading vaccines
LSHTM estimate of 1.2 (with a doubling time of 12 days) has not been updated since 15 July https://t.co/zSBhwypAoP… https://t.co/koaOOKykzR
I did nothing significant to contribute during this pandemic; I don't do anything significant to 

In [59]:
import numpy as np 
import pandas as pd 
import re  
import nltk # an amazing library to play with natural language
nltk.download('stopwords')  
from nltk.corpus import stopwords 


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [61]:
tweets = pd.read_csv("https://raw.githubusercontent.com/kolaveridi/kaggle-Twitter-US-Airline-Sentiment-/master/Tweets.csv")
print(tweets)

                 tweet_id  ...               user_timezone
0      570306133677760513  ...  Eastern Time (US & Canada)
1      570301130888122368  ...  Pacific Time (US & Canada)
2      570301083672813571  ...  Central Time (US & Canada)
3      570301031407624196  ...  Pacific Time (US & Canada)
4      570300817074462722  ...  Pacific Time (US & Canada)
...                   ...  ...                         ...
14635  569587686496825344  ...                         NaN
14636  569587371693355008  ...                         NaN
14637  569587242672398336  ...                         NaN
14638  569587188687634433  ...  Eastern Time (US & Canada)
14639  569587140490866689  ...                         NaN

[14640 rows x 15 columns]


In [62]:
X = tweets.iloc[:, 10].values  
y = tweets.iloc[:, 1].values

print(X)

['@VirginAmerica What @dhepburn said.'
 "@VirginAmerica plus you've added commercials to the experience... tacky."
 "@VirginAmerica I didn't today... Must mean I need to take another trip!"
 ... '@AmericanAir Please bring American Airlines to #BlackBerry10'
 "@AmericanAir you have my money, you change my flight, and don't answer your phones! Any other suggestions so I can make my commitment??"
 '@AmericanAir we have 8 ppl so we need 2 know how many seats are on the next flight. Plz put us on standby for 4 people on the next flight?']


In [63]:
processed_tweets = []
 
for tweet in range(0, len(X)):  
    # Remove all the special characters
    processed_tweet = re.sub(r'\W', ' ', str(X[tweet]))
 
    # remove all single characters
    processed_tweet = re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_tweet)
 
    # Remove single characters from the start
    processed_tweet = re.sub(r'\^[a-zA-Z]\s+', ' ', processed_tweet) 
 
    # Substituting multiple spaces with single space
    processed_tweet= re.sub(r'\s+', ' ', processed_tweet, flags=re.I)
 
    # Removing prefixed 'b'
    processed_tweet = re.sub(r'^b\s+', '', processed_tweet)
 
    # Converting to Lowercase
    processed_tweet = processed_tweet.lower()
 
    processed_tweets.append(processed_tweet)

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer  
tfidfconverter = TfidfVectorizer(max_features=2000, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))  
X = tfidfconverter.fit_transform(processed_tweets).toarray()


### Task
**The below code is showing how to classify the tweet using Random Forest Classifer. Can you please now create a LSTM model and do the same job as we did during the lab?**

In [65]:
from sklearn.ensemble import RandomForestClassifier
text_classifier = RandomForestClassifier(n_estimators=100, random_state=0)  
text_classifier.fit(X, y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [66]:
for tweet in all_tweets:
    # Remove all the special characters
    processed_tweet = re.sub(r'\W', ' ', tweet)
 
    # remove all single characters
    processed_tweet = re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_tweet)
 
    # Remove single characters from the start
    processed_tweet = re.sub(r'\^[a-zA-Z]\s+', ' ', processed_tweet) 
 
    # Substituting multiple spaces with single space
    processed_tweet= re.sub(r'\s+', ' ', processed_tweet, flags=re.I)
 
    # Removing prefixed 'b'
    processed_tweet = re.sub(r'^b\s+', '', processed_tweet)
 
    # Converting to Lowercase
    processed_tweet = processed_tweet.lower()
 
    sentiment = text_classifier.predict(tfidfconverter.transform([ processed_tweet]).toarray())
    print(processed_tweet ,":", sentiment)


we can help beat covid19 together join me and take one minute day to help fight the outbreak in our community https co qhwygjnhqk : ['negative']
 beatric84037839 inthebubblepod aslavitt pfizer albertbourla but covid19 is over with you us therein lies the problem  : ['negative']
fully vaccinated travellers from the us and eu countries will no longer need to undergo 10 day compulsory https co qf0rdjo9ij : ['neutral']
getting vaccinated is crucial to protecting everyone health we re proud of scc amcollsurgeons amp aao_ophth fo https co t9ej3hkvv6 : ['neutral']
for my mental health m blocking everyone on my newsfeed that expresses ignorant ass commentary about sars cov 2 https co vxv7w72s6j : ['neutral']
 nypost cdc warns covid19 may be few mutations away from evading vaccines : ['negative']
lshtm estimate of 1 2 with doubling time of 12 days has not been updated since 15 july https co zsbhwypaop https co koaookykzr : ['negative']
i did nothing significant to contribute during this pandemi

In [67]:
import tensorflow as tf
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

data = y
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

encoded = tf.keras.utils.to_categorical(integer_encoded)
print(encoded)
print(X)

['neutral' 'positive' 'neutral' ... 'neutral' 'negative' 'neutral']
[1 2 1 ... 1 0 1]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [68]:

from keras.layers import LSTM
from keras.models import Sequential
from keras.losses import categorical_crossentropy
from keras.layers import Embedding, Dense


max_features = 10000
model = Sequential()
model.add(Embedding(max_features, 32))
model.add(LSTM(32))
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='Adam',
loss='categorical_crossentropy',
metrics=['acc'])

history = model.fit(X, encoded,
                    epochs=10,
                    batch_size=128,
                    validation_split=0.2)



Epoch 1/10
92/92 [==============================] - 138s 1s/step - loss: 1.0032 - acc: 0.5630 - val_loss: 0.8178 - val_acc: 0.7128
Epoch 2/10
92/92 [==============================] - 135s 1s/step - loss: 0.9378 - acc: 0.6079 - val_loss: 0.8130 - val_acc: 0.7128
Epoch 3/10
92/92 [==============================] - 135s 1s/step - loss: 0.9493 - acc: 0.5996 - val_loss: 0.8276 - val_acc: 0.7128
Epoch 4/10
92/92 [==============================] - 135s 1s/step - loss: 0.9390 - acc: 0.6078 - val_loss: 0.8105 - val_acc: 0.7128
Epoch 5/10
92/92 [==============================] - 135s 1s/step - loss: 0.9413 - acc: 0.6064 - val_loss: 0.8267 - val_acc: 0.7128
Epoch 6/10
92/92 [==============================] - 135s 1s/step - loss: 0.9281 - acc: 0.6156 - val_loss: 0.8269 - val_acc: 0.7128
Epoch 7/10
92/92 [==============================] - 134s 1s/step - loss: 0.9376 - acc: 0.6080 - val_loss: 0.8437 - val_acc: 0.7128
Epoch 8/10
92/92 [==============================] - 135s 1s/step - loss: 0.9473 - a

In [54]:
(test_loss,train_acc) = model.evaluate(X,encoded)

458/458 [==============================] - 64s 140ms/step - loss: 0.9188 - acc: 0.6269
